### PR TITLE
Added the Dynamic Component Test

### PR DESCRIPTION
**Pull request by AndreiTeodorLazar**
This PR adds this [test ](https://github.com/spatialos/UnrealGDK/pull/2488) in the SpatialNetworkingMap.

Note that the change to the map was done from 4.24.

### CODE REVIEW

**Comment by mironec** [comment]
Conflict apparently - maybe the move to CI_Fast?

**Comment by AndreiTeodorLazar** [comment]
> Conflict apparently - maybe the move to CI_Fast?

Just solved it, should be good now.

**Comment by AndreiTeodorLazar** [comment]
> Conflict apparently - maybe the move to CI_Fast?

Yeah, that and also the RepNotify test.

**Review by mironec — APPROVED** [review]
Good change, I approve

**Pull request merged**
