### PR TITLE
Fixed BP and map warnings

### PR DESCRIPTION
**Pull request by improbable-dmitrii**
Removed two unused BP properties (LockingToken, INVALID_LOCK_TOKEN) in Offloading cube that conflicted with a C++ property
Set the Tiny Offloading Gym to use offloaded world settings.

### CODE REVIEW

**Comment by improbable-dmitrii** [comment]
BP diff screenshot: 
image

**Review by simonsarginson — APPROVED** [review]

**Comment by mironec** [comment]
What version of the engine was used to save the new asset?
Not sure how often the asset is used/if the maps that use it need to be runnable in 4.24/4.25.

**Comment by improbable-dmitrii** [comment]
It did it on 4.26 - and this is a nice catch, I'll try and resave this in 4.24.

**Comment by improbable-dmitrii** [comment]
Resaved in 4.24, had to modify offloading settings as they were saved in 4.25.

**Comment by MatthewSandfordImprobable** [comment]
What needed modifying in BP_oflgym_Offloaded_Settings.uasset?

**Comment by improbable-dmitrii** [comment]
I've recreated it in 4.24, no contents changed.

**Review by MatthewSandfordImprobable — APPROVED** [review]

**Comment by improbable-dmitrii** [comment]
Merging to 0.12.0-rc, ran tests on my machine.

**Pull request merged**
