### PR TITLE
Instrument latency paths

### PR DESCRIPTION
**Pull request by improbable-danny**
Cross-server cube: https://blueprintue.com/blueprint/68xifu61/
Event tracer character: https://blueprintue.com/blueprint/kbjxbm93/

### CODE REVIEW

**Comment by MatthewSandfordImprobable** [comment]
Do we need the property update on the cross server cube?

**Comment by MatthewSandfordImprobable** [comment]
What were the changes to ET character?

**Comment by improbable-danny** [comment]
> Do we need the property update on the cross server cube?
I think so for cross-server property update tests

> What were the changes to ET character?
There ended up being no changes to the character, the cube was placed directly in the level for cross-server functionality. I could change the FName variables though to match the cube ones (I reverted accidently, although there isn't a need to change them so not sure)

**Comment by MatthewSandfordImprobable** [comment]
Ahh so the blueprint changes "Event tracer character" are for the latency character.

**Review by MatthewSandfordImprobable — APPROVED** [review]

**Review by joshuahuburn — APPROVED** [review]

**Pull request merged**
