### PR TITLE
[UNR-3206] Fix NetReferenceTestGym to manually spawn controller after authority has been gained

### PR DESCRIPTION
**Pull request by ImprobableNic**
Was broken because of https://improbableio.atlassian.net/browse/UNR-3231

Fixed it to not use this code path anymore and explicitely spawn a player controller when authority has been gained.
CheckoutPawn
CheckoutPawnController

### CODE REVIEW

**Comment by joshuahuburn** [comment]
Can we have a couple screenshots of the BPs?

**Comment by m-samiec** [comment]
Why is the "delay" necessary?

**Comment by ImprobableNic** [comment]
Can't connect the output pin to the input pin otherwise.

**Comment by m-samiec** [comment]
> Can't connect the output pin to the input pin otherwise.

Really? There's an increment inbetween and it's an async action, so I don't see what the problem would be. Whats the error?

**Comment by ImprobableNic** [comment]
> Really? There's an increment inbetween and it's an async action, so I don't see what the problem would be. Whats the error?

IIRC, it just crashes at runtime with a blueprint VM infinite loop error.

**Pull request merged**
