### PR TITLE
Adding worker_id to event trace events

### PR DESCRIPTION
**Pull request by improbable-danny**
Refactored the "latency." traces to go through this new function, which adds in the worker_id

image
image

### CODE REVIEW

**Comment by m-samiec** [comment]
Inside Trace Event Basic with Worker ID, the message itself it blank, can we add something their for more detail?

**Comment by MatthewSandfordImprobable** [comment]
I assume we use the "Trace Event Basic with Worker ID" in all the "start" ET events (all events of type "latency.server_rpc")?

**Review by MatthewSandfordImprobable — APPROVED** [review]

**Comment by improbable-danny** [comment]
>I assume we use the "Trace Event Basic with Worker ID" in all the "start" ET events (all events of type "latency.server_rpc")?
Yeah, I replaced all "latency." events with this

**Comment by improbable-danny** [comment]
> Inside Trace Event Basic with Worker ID, the message itself it blank, can we add something their for more detail?
Modified to this and added messages (the names we used previously for USpatialLatencyTracer) 
image

**Review by m-samiec — APPROVED** [review]

**Pull request merged**
