### PR TITLE
World composition gym

### PR DESCRIPTION
**Pull request by samiwh**
A world composition gym.

Move towards each circle to load a level.
Move away from the circles to unload the level.

image

### CODE REVIEW

**Comment by m-samiec** [comment]
Might be worth exercising additional level types here? Add Actor's with bNetLoadOnClient set to false. Add a dormant Actor. Add an actor with a component. Thoughts?

**Comment by samiwh** [comment]
Seems like a good idea. Can do.

**Comment by samiwh** [comment]
What if we did something like this
image

**Comment by samiwh** [comment]
Otherwise I'd suggest spending a bit more time on it and adding several levels that contain different things you can walk up to. Which seems like a good thing to have anyway.

**Comment by samiwh** [comment]
Changed to a series of levels.

**Pull request merged**
